services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    container_name: frontendContainer
    ports:
      - "8000:80"
    networks:
      - examenInternal

  backend:
    build:
      dockerfile: backend.Dockerfile
    container_name: backendContainer
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - examenInternal

  mysql:
    build:
      dockerfile: database.Dockerfile
    container_name: databaseContainer
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - databaseVolume:/var/lib/mysql
    networks:
      - examenInternal

networks:
  examenInternal:

volumes:
  databaseVolume:   